blogpost-project/blogpost/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
import debug_toolbar
from django.conf.urls.static import static
from django.conf import settings
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("diary.urls")),
    path("schema", SpectacularAPIView.as_view(), name="schema"),
    path(
        "docs/",
        SpectacularSwaggerView.as_view(
            template_name="swagger-ui.html", url_name="schema"
        ),
        name="swagger-ui",
    ),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogspot-project/blogspot/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
import debug_toolbar
from django.conf.urls.static import static
from django.conf import settings
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("diary.urls")),
    path("schema", SpectacularAPIView.as_view(), name="schema"),
    path(
        "docs/",
        SpectacularSwaggerView.as_view(
            template_name="swagger-ui.html", url_name="schema"
        ),
        name="swagger-ui",
    ),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
import debug_toolbar
from django.conf.urls.static import static
from django.conf import settings
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("diary.urls")),
    path("schema", SpectacularAPIView.as_view(), name="schema"),
    path(
        "docs/",
        SpectacularSwaggerView.as_view(
            template_name="swagger-ui.html", url_name="schema"
        ),
        name="swagger-ui",
    ),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    # Serve media files in development only
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import include, path
from .views import (
    HomeView,
    HomeViewLikeOrdered,
   

    SignUp,
    Login,
    PasswordReset,
    CustomPasswordResetConfirmView,

    AuthorListView,
    AuthorDetailView,

    PostListView,
    PostCreateView,
    PostDetailView,
    PostUpdateView,
    PostDeleteView,

    RootAPIView,

    UserListAPIView,
    UserDetailAPIView,
    TokenRecoveryAPIView,
    MyTokenObtainPairView,
    MyTokenRefreshView,

    PostAPIView,
    PostDetailAPIView,

    LikeAPIView,
    LikeCreateDestroyAPIView,
    LikeDetailAPIView,
    getLikes,
)
from django.contrib.auth.views import LogoutView
from rest_framework_simplejwt.views import TokenObtainPairView
from rest_framework_simplejwt.views import TokenVerifyView


urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("like_ordered/", HomeViewLikeOrdered.as_view(), name="home-like-ordering"),

    path("signup/", SignUp.as_view(), name="signup"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("password_reset/", PasswordReset.as_view(), name="password_reset"),
    path("reset/<uidb64>/<token>/", CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    # Here we include some other Django default auth views like PasswordChangeView and so on.
    path("", include("django.contrib.auth.urls")),

    path("authors/", AuthorListView.as_view(), name="author-list"),
    path("authors/<sortfield>/", AuthorListView.as_view(), name="author-list"),
    path("author/<int:pk>/", AuthorDetailView.as_view(), name="author-detail"),

    path("posts/", PostListView.as_view(), name="post-list"),
    path("posts/add/", PostCreateView.as_view(), name="post-add"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("posts/<int:pk>/update/", PostUpdateView.as_view(), name="post-update"),
    path("posts/<int:pk>/delete/", PostDeleteView.as_view(), name="post-delete"),

    path("api/v1/", RootAPIView.as_view(), name="root-api"),

    path("api/v1/users/", UserListAPIView.as_view(), name="user-list-create-api"),
    path("api/v1/users/<int:pk>/", UserDetailAPIView.as_view(), name="user-detail-update-destroy-api"),
    path("api/v1/auth/login/", TokenObtainPairView.as_view(), name="login-api"),
    path("api/v1/mylogin/", MyTokenObtainPairView.as_view(), name="my-login-api"),
    path('api/v1/auth/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path("api/v1/auth/token-refresh/", MyTokenRefreshView.as_view(), name="token-refresh-api"),
    path("api/v1/auth/token-recovery/", TokenRecoveryAPIView.as_view(), name="token-recovery-api"),

    path("api/v1/posts/", PostAPIView.as_view(), name="post-list-create-api"),
    path("api/v1/posts/<int:pk>/", PostDetailAPIView.as_view(), name="post-detail-api"),

    path("api/v1/likes/", LikeAPIView.as_view(), name="like-list-api"),
    path("api/v1/likes/<int:pk>/", LikeDetailAPIView.as_view(), name="like-detail-api"),
    path("api/v1/likes/add/", LikeCreateDestroyAPIView.as_view(), name="like-create-destroy-post-api"),
    path("likes_count_on_post/<int:post_id>/", getLikes, name="like-count-on-post"),
]

diary/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.urls import reverse
from .validators import MyUnicodeUsernameValidator, profanity
from django.utils.translation import gettext_lazy as _
from pathlib import Path
from PIL import Image, ImageOps


class CustomUser(AbstractUser):

    # make email field unique and required (not blank)

    email = models.EmailField(
        _("email address"), 
        unique=True,  
        error_messages={
            "unique": _("A user with that email already exists."),
        },
    )

    last_request = models.DateTimeField(_("last request"), blank=True, null=True)
    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[MyUnicodeUsernameValidator()],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )


class Post(models.Model):
    title = models.CharField(max_length=100, validators=[profanity])
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(validators=[profanity])
    image = models.ImageField(upload_to='diary/images/', blank=True)
    thumbnail = models.ImageField(upload_to='diary/images/thumbnails/', blank=True, null=True, editable=False, max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=True)

    def save(self, *args, **kwargs):

        super().save(*args, **kwargs)

        if self.image:
            with Image.open(self.image.path) as img:
                img_format = img.format
                max_size = (2000, 2000)

                img_copy = img.copy()
                img_copy.thumbnail(max_size, Image.Resampling.LANCZOS)
                img_copy.save(self.image.path, format=img_format)

                ##########################################
                # Generate the thumbnail image

                thumbnail_size = (300, 300)
                thumb_img = ImageOps.fit(
                    img_copy,
                    thumbnail_size,
                    method=Image.Resampling.LANCZOS,
                    centering=(0.5, 0.5),
                )

                # Get the directory path for thumbnails
                thumbnail_dir = Path(settings.MEDIA_ROOT) / 'diary/images/thumbnails'
                thumbnail_dir.mkdir(parents=True, exist_ok=True)

                # Get the original filename
                original_filename = Path(self.image.name).name

                # Generate the thumbnail path
                thumbnail_path = thumbnail_dir / f"thumb_{original_filename}"

                # Save the thumbnail image
                thumb_img.save(thumbnail_path, format=img_format)

                # Calculate the relative path of the thumbnail image
                thumbnail_rel_path = thumbnail_path.relative_to(settings.MEDIA_ROOT)

                # Update the thumbnail field in the database
                self.thumbnail.name = str(thumbnail_rel_path)
                super().save(update_fields=['thumbnail'], *args, **kwargs)

    class Meta:
        ordering = ['-updated']

    def __str__(self) -> str:
        return f'{self.author.username}: {self.title}'
    
    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.id})


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [models.UniqueConstraint(fields=['user', 'post'], name='unique_like')]

    def __str__(self) -> str:
        return f'{self.user.username}: {self.post.title}'

diary/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm, UsernameField, PasswordResetForm, SetPasswordForm
from django.contrib.auth import password_validation
from django.utils.translation import gettext_lazy as _
from .models import CustomUser, Post

class CustomUserCreationForm(UserCreationForm):

    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class': "form-control"}),
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class': "form-control"}),
        strip=False,
    )
    email = forms.EmailField(
        label="Email",
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email", 'class': "form-control"}),
    )

    agree = forms.BooleanField(
                            label='Agree',
                            required = True,
                            disabled = False,
                            widget=forms.widgets.CheckboxInput(
                                attrs={'class': 'checkbox-inline'}),
                                help_text = "I allow to use Cookies on that web-site",
                                error_messages ={'required':'Please check the box'}
                            )

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'email', 'agree')
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
            'agree': forms.CheckboxInput(attrs={'class':'form-control'}),
        }


class CustomAuthenticationForm(AuthenticationForm):

    username = UsernameField(widget=forms.TextInput(attrs={"autofocus": True, 'class':'form-control'}))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", 'class':'form-control'}),
    )

class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={"autocomplete": "email", 'class':'form-control'}),
    )


class CutomSetPasswordForm(SetPasswordForm):

    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class':'form-control'}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class':'form-control'}),
    )


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = 'title', 'content', 'image', 'published'
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'content': forms.Textarea(attrs={'class':'form-control'}),
            'image': forms.FileInput(attrs={'class':'form-control'}),
            'published': forms.CheckboxInput(attrs={'class':'form-check-input'}),
        }
        labels = {
            'published': 'Publish'
        }


class UpdatePostForm(AddPostForm):

    class Meta(AddPostForm.Meta):
        help_texts = {
            'image': _("if you don't wish to change the image - just left it unattached here"),
        }

diary/templates/diary/add-post.html
{% extends 'diary/base.html' %}

{% block title %} add post {% endblock %}

{% block content %}


<form method="post" class="auth-form" enctype="multipart/form-data" id="myForm" onsubmit="return resizeImageAndSubmitForm()">
    {% csrf_token %}

    {{ form.non_field_errors }}
    
    <div class="mb-3">
        <label for="{{ form.title.id_for_label }}" class="form-label">{{form.title.label}}:</label> 
        {{ form.title }}
    </div>
    <div class="form-text">{{form.title.errors}}</div>

    <div class="mb-3">
        <label for="{{ form.content.id_for_label }}" class="form-label">{{form.content.label}}:</label> 
        {{ form.content }}
    </div>
    <div class="form-text">{{form.content.errors}}</div>

    <div class="mb-3">
        <label for="{{ form.image.id_for_label }}" class="form-label">{{form.image.label}}:</label> 
        {{ form.image }}
    </div>
    <div class="form-text">{{form.image.errors}}</div>

    <div class="mb-3">
        <label for="{{ form.published.id_for_label }}" class="form-check-label">{{form.published.label}}:</label> 
        {{ form.published }}
    </div>
    <div class="form-text">{{form.published.errors}}</div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

{% endblock %}

diary/templates/diary/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta property="og:url" content="{% url 'home' %}"/>
  <meta property="og:title" content="Social Network"/>
  <meta property="og:description" content="Share your discovery with the world"/>
  <title>{% block title %}postways{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'diary/style.css' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'diary/images/favicon/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'diary/images/favicon/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'diary/images/favicon/favicon-16x16.png' %}">
  <link rel="manifest" href="{% static 'diary/images/favicon/site.webmanifest' %}">
  <link rel="mask-icon" href="{% static 'diary/images/favicon/safari-pinned-tab.svg' %}" color="#455458">
  <meta name="msapplication-TileColor" content="#fcfcfc">
  <meta name="theme-color" content="#ffffff">  
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@1,300&display=swap" rel="stylesheet">
</head>

<body class="container" style="max-width: 991px;">
  <header>
    <nav class="navbar fixed-top navbar-expand-lg container" style="max-width: 991px; background-color: #f2f3f4;">
      <div class="container-fluid">
        <a class="navbar-brand {% if view.template_name == 'diary/index.html' %}selected{% endif %}" href="{% url 'home' %}"><img alt="logo" src="{% static 'diary/images/logo.svg' %}">postways</a>
        {% if user.is_authenticated %}
        <a class="nav-link active text-dark {% if view.template_name == 'diary/add-post.html' %}selected{% endif %}" href="{% url 'post-add' %}">Add post &#x1F4CC;</a>
        {% else %}
        <a class="nav-link active text-dark {% if view.template_name == 'registration/login.html' %}selected{% endif %}" href="{% url 'login' %}">Add post &#x1F4CC;</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Summary
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'author-list' %}">Authors</a></li>
                <li><a class="dropdown-item" href="{% url 'post-list' %}">Posts</a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="{% url 'swagger-ui' %}">OpenApi-Swagger</a></li>
              </ul>
            </li>
          </ul>
          <form class="d-flex" role="search">
            {% if request.user.is_authenticated %}
            <button type="button" id="user" class="btn btn-sm btn-outline-secondary {% if view.template_name == 'diary/customuser_detail.html' %}active{% endif %}"
              onclick="location.href='{% url 'author-detail' user.pk %}';">{{user.username}}</button>
            <button type="button" class="btn btn-sm btn-outline-secondary"
              onclick="location.href='{% url 'logout' %}';">Logout</button>
            {% else %}
            <button type="button" class="btn btn-sm btn-outline-secondary {% if view.template_name == 'registration/signup.html' %}active{% endif %}"
              onclick="location.href='{% url 'signup' %}';">Signup</button>
            <button type="button" class="btn btn-sm btn-outline-secondary {% if view.template_name == 'registration/login.html' %}active{% endif %}"
              onclick="location.href='{% url 'login' %}';">Login</button>
            {% endif %}
          </form>
        </div>
      </div>
    </nav>
  </header>
  <br>
  <br>
  <br>
  <section>
    {% block content %}
    {% endblock %}

    {% if is_paginated %}
    <nav>
      <ul class="pagination justify-content-center">

          {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?page=1" class="page-link">First</a>
        </li>
        <li class="page-item">
          <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo;</a>
        </li>
        {% endif %}

        <li class="page-item disabled">
        
          <a href="#" class="page-link">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a>
        </li>
        <li class="page-item">
          <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">Last</a>
        </li>
        {% endif %}

      </ul>
    </nav>
    {% endif %}
  </section>
  <div id="django-debug" style="display: none;">
    <pre>{% debug | escape %}</pre>
  </div>
  <script src="{% static 'diary/fetch.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
    crossorigin="anonymous"></script>
</body>

</html>

diary/templates/diary/customuser_detail.html
{% extends 'diary/base.html' %}

{% block title %} author#{{object.pk}} {{ object.username }} {% endblock %}

{% block content %}

{% load diary_tags %}
 
<h2>
    {% if user.is_staff %}
    {{object.username}} posts:
    {% else %}
    My posts:
    {% endif %}
    {{ object.post_set.count }}</h2> 
<br>

{% for post in  page_obj %}
<div class="post">
<div>
<a href="{% url 'post-detail' post.pk %}"><h3 class="title">{{ post.title }}</h3></a>
<p class="author">{{ post.created|date }} at {{ post.created|time:"H:i" }}
    {% if not post.published %}
    <br><b>*unpublished</b>
    {% endif %}
<p class="title">
    <a href="{% url 'post-detail' post.pk %}" class="post-content">
    <span class="short-post">{{ post.content|truncatechars:100 }}</span>
    </a>
    <br>
    <a href="{% url 'like-create-destroy-post-api' %}" id="{{ post.id }}" class="like">
        {% autoescape off %}{% like_or_unlike user post %}{% endautoescape %} {{ post.like_set.count }}
    </a>
</p>
</div>

{% if post.image %}
<div>
<a href="{% url 'post-detail' post.pk %}">
<img src="{{ post.image.url }}" alt="" class="rounded float-left post-img">
</a>
</div>
{% endif %}

</div>
<hr>
<br>
{% endfor %}


{% endblock %}

diary/templates/diary/customuser_list.html
{% extends 'diary/base.html' %}

{% block title %} Authors {% endblock %}

{% block content %}

<h2>All authors</h2>
<br>


<table class="table table-hover author-list">
    <thead>
      <tr class="table-light">
        <th scope="col"><a href="{% url 'author-list' %}id/">#</a></th>
        <th scope="col"><a href="{% url 'author-list' %}username/">Username</a></th>
        <th scope="col"><a href="{% url 'author-list' %}date_joined/">Date joined</a></th>
        <th scope="col"><a href="{% url 'author-list' %}post__count/">Total posts</a></th>
        <th scope="col"><a href="{% url 'author-list' %}like__count/">Likes provided</a></th>
        <th scope="col"><a href="{% url 'author-list' %}post__like__count/">Likes recieved</a></th>
      </tr>

      <tr class="table-light">
        <th scope="col" class="link-secondary">{{ object_list.count }}</th>
        <th scope="col" class="link-secondary"></th>
        <th scope="col" class="link-secondary"></th>
        <th scope="col" class="link-secondary">{{ posts }}</th>
        <th scope="col" class="link-secondary">{{ likes }}</th>
        <th scope="col" class="link-secondary"></th>
      </tr>

    </thead>
    <tbody>
      {% for author in  object_list %}
      <tr>
        <th scope="row">{{ author.pk }}</th>
        <td><a href="{% url 'author-detail' author.pk %}" class="title">{{ author.username }}</a></td>
        <td>{{ author.date_joined|date:"d/m/Y" }}</td>
        <td> {{ author.post__count }} </td>
        <td> {{ author.like__count }} </td>
        <td> {{ author.post__like__count }} </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>



{% endblock %}

diary/templates/diary/index.html
{% extends 'diary/base.html' %} 

{% block title %} postways {% endblock %}

{% block content %} 


<div class="left">
<a href="{% url 'home' %}" style="color:black;"> 
    {% if ordering == 'fresh' %}
    <u>fresh</u>
    {% else %}
    fresh
    {% endif %}
</a>
&nbsp;&nbsp;|&nbsp;&nbsp;
<a href="{% url 'home-like-ordering' %}" style="color:black;">  
    
    {% if ordering == 'liked' %}
    <u>popular</u>
    {% else %}
    popular
    {% endif %}
</a>
</div>
<hr>
<br>
{% for post in object_list %}
<div class="post">
    
    <div>
        <a href="{% url 'post-detail' post.pk %}">
            <h3 class="title">{{ post.title }}</h3>
        </a>
        <p class="author">
            <a href="{% url 'author-detail' post.author.pk %}">{{ post.author.username }}</a>
            <br>
            {{post.created|date }} at {{ post.created|time:"H:i" }}
        </p>
        <p class="title">
            <a href="{% url 'post-detail' post.pk %}" class="post-content short-post">
                <span class="short-post">{{ post.content|truncatechars:100 }}</span>
            </a>
            <br>
            {% if user.is_authenticated and post in liked_by_user %}
            <a href="{% url 'like-create-destroy-post-api' %}" id="{{ post.id }}" class="like">&#10084; {{ post.like__count }}</a>
            {% elif user.is_authenticated %}
            <a href="{% url 'like-create-destroy-post-api' %}" id="{{ post.id }}" class="like">&#9825; {{ post.like__count }}</a>
            {% else %}
            <a href="{% url 'login' %}" id="{{ post.id }}" class="like">&#9825; {{ post.like__count }}</a>
            {% endif %}
        </p>
    </div>

    {% if post.image %}
    <div>
        <a href="{% url 'post-detail' post.pk %}">
            <img src="{{ post.thumbnail.url }}" alt="" class="rounded float-left post-img">
        </a>
    </div>
    {% endif %}
    
</div>
<hr>
<br>
{% endfor %} 

{% endblock %}

diary/templates/diary/post-delete.html
{% extends 'diary/base.html' %}

{% block title %} delete post {% endblock %}

{% block content %}


    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        
        <p>Are you sure you want to delete post <b>{{ object }}</b> ?</p>

        <div style="display:none"> {{ form }} </div>
       
        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
    </form>

    
{% endblock %}

diary/templates/diary/post-update.html
{% extends 'diary/base.html' %}

{% block title %} update post {% endblock %}

{% block content %}


<form method="post" class="auth-form" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.non_field_errors }}
    
    <div class="mb-3">
        <label for="{{ form.title.id_for_label }}" class="form-label">{{form.title.label}}:</label> 
        {{ form.title }}
    </div>
    <div class="form-text">{{form.title.errors}}</div>

    <div class="mb-3">
        <label for="{{ form.content.id_for_label }}" class="form-label">{{form.content.label}}:</label> 
        {{ form.content }}
    </div>
    <div class="form-text">{{form.content.errors}}</div>

    <div class="mb-3">
        <label for="{{ form.image.id_for_label }}" class="form-label">{{form.image.label}}:<div class="form-text">*{{form.image.help_text}}</div></label> 
        {{ form.image }}
    </div>
    <div class="form-text">{{form.image.errors}}</div>

    <div class="mb-3">
        <label for="{{ form.published.id_for_label }}" class="form-check-label">{{form.published.label}}:</label> 
        {{ form.published }}
    </div>
    <div class="form-text">{{form.published.errors}}</div>

    <button type="submit" class="btn btn-primary">submit</button>
</form>

{% endblock %}